import { Field } from '../../components/Fields'
import { AttemptFields } from '../mechanics/PrepareBeat'
import type { Beat, TableVersion } from '../mechanics/types'

export function RecipeBeat({ value, tables, onChange }: { value: Beat; tables: TableVersion[]; onChange: (value: Beat) => void }) {
  const patch = (changes: Partial<Beat>) => onChange({ ...value, ...changes })
  return <fieldset className="form-stack"><legend>Chance preparation for this draft</legend><Field label="Completed beat for this recipe" maxLength={500} value={value.label} onChange={event => patch({ label: event.target.value })} /><label className="field"><span>Recipe event family</span><select aria-label="Recipe event family" value={value.family} onChange={event => patch({ family: event.target.value as Beat['family'] })}><option value="narrative-push">Narrative Push</option><option value="encounter">Encounter</option><option value="none">Handling / optional tables only</option></select></label><div className="recipe-field-grid">{([['completed', 'This meaningful beat is complete'], ['waiting_for_player', 'The player still has an unfinished choice'], ['protected', 'Keep this moment uninterrupted'], ['resolves_event', 'The previous generated event is resolved'], ['new_scene', 'This begins a new scene']] as const).map(([key, label]) => <label className="check-row" key={key}><input type="checkbox" checked={value[key]} onChange={event => patch({ [key]: event.target.checked })} />{label}</label>)}</div>
    <details><summary>Attempted action & optional tables</summary><div className="form-stack"><label className="check-row"><input type="checkbox" checked={!!value.attempt} onChange={event => patch({ attempt: event.target.checked ? { action: '', actor: '', domain: '', level: 0, fractured: false, prepared: false } : null })} />Resolve an already chosen action</label>{value.attempt && <AttemptFields value={value.attempt} onChange={attempt => patch({ attempt })} />}{tables.filter(table => ['extra', 'texture'].includes(table.definition.purpose)).map(table => <label className="check-row" key={table.table_id}><input type="checkbox" checked={value.extras.includes(table.table_id)} onChange={event => patch({ extras: event.target.checked ? [...value.extras, table.table_id] : value.extras.filter(key => key !== table.table_id) })} />{table.definition.name}</label>)}</div></details><p className="subtle">This chance result belongs to the draft. Applying its text does not advance accepted Story mechanics.</p>
  </fieldset>
}
