import { Field } from '../../components/Fields'
import type { RecipeContent } from './types'
import type { RecipeOptions } from './recipeEditorTypes'

const mechanisms = [['narrative_push', 'Narrative Push'], ['encounter', 'Encounter'], ['handling', 'Handling an attempted action']] as const
const components = [['proficiency', 'Domain proficiency'], ['fracture', 'Fracture'], ['preparation', 'Preparation'], ['subresults', 'Handling outcome shape'], ['carriers', 'Outcome carrier'], ['textures', 'Texture draws'], ['pressure_cap', 'Pressure cap'], ['domain_progression', 'Domain progression']] as const

export function RecipeSettings({ value, options, onChange }: { value: RecipeContent; options: RecipeOptions; onChange: (value: RecipeContent) => void }) {
  return <details className="advanced-settings"><summary>Task switches & chance settings</summary><div className="form-stack"><RecipeSwitches value={value.disabled_tasks} options={options.tasks} onChange={disabled_tasks => onChange({ ...value, disabled_tasks })} /><RecipeRandomness value={value.randomness} defaults={options.randomness_defaults} onChange={randomness => onChange({ ...value, randomness })} /></div></details>
}

function RecipeSwitches({ value, options, onChange }: { value: string[]; options: RecipeOptions['tasks']; onChange: (value: string[]) => void }) {
  const toggle = (key: string) => onChange(value.includes(key) ? value.filter(item => item !== key) : [...value, key])
  const retained = value.filter(key => !options.some(option => option.key === key))
  return <section className="form-stack"><h3>Tasks to disable for this recipe</h3><p className="subtle">Unlisted tasks inherit Story settings. A recipe cannot turn on a task disabled by the workspace. These choices do not change saved Story or workspace settings.</p><div className="recipe-field-grid">{options.map(option => <label className="check-row" key={option.key}><input type="checkbox" checked={value.includes(option.key)} onChange={() => toggle(option.key)} />Disable {option.name}<small>{option.key}</small></label>)}</div>{retained.map(key => <label className="check-row" key={key}><input type="checkbox" checked onChange={() => toggle(key)} />Retained disabled task · {key}</label>)}</section>
}

export function RecipeRandomness({ value, defaults, onChange, run = false }: { value: RecipeContent['randomness']; defaults: RecipeOptions['randomness_defaults']; onChange: (value: RecipeContent['randomness']) => void; run?: boolean }) {
  const settings = { ...defaults, ...value }
  const mode = value === null ? 'inherit' : settings.enabled ? 'custom' : 'off'
  const changeMode = (mode: string) => onChange(mode === 'inherit' ? null : { ...settings, enabled: mode === 'custom' })
  const patch = (change: Record<string, unknown>) => onChange({ ...settings, ...change })
  const subject = run ? 'run' : 'recipe'
  return <section className="form-stack"><h3>Chance settings</h3><label className="field"><span>{run ? 'Chance for this run' : 'Recipe randomness'}</span><select aria-label={run ? 'Chance for this run' : 'Recipe randomness'} value={mode} onChange={event => changeMode(event.target.value)}><option value="inherit">{run ? 'Inherit recipe / Story chance settings' : "Inherit the Story's chance settings"}</option><option value="off">Automatic randomness off for this {subject}</option><option value="custom">Use {subject} chance settings</option></select></label><p className="subtle">{run ? 'A draft run records one chance result after you review and save it. Reviews and wording revisions do not introduce chance events. Automatic acceptance assessment is inapplicable to this proposal workflow.' : 'Saving or browsing a recipe never rolls. To use its chance choices, select text and choose Run recipe.'}</p>
    {value !== null && <><div className="recipe-field-grid">{mechanisms.map(([key, label]) => <label className="check-row" key={key}><input type="checkbox" checked={settings[key]} onChange={event => patch({ [key]: event.target.checked })} />{label}</label>)}</div><div className="recipe-field-grid"><Field label="Recipe event chance (%)" type="number" min={0} max={100} value={settings.chance} onChange={event => patch({ chance: Number(event.target.value) })} /><Field label="Recipe beats of breathing room" type="number" min={0} max={100} value={settings.cooldown} onChange={event => patch({ cooldown: Number(event.target.value) })} /><Field label="Recipe major disruptions per scene" type="number" min={0} max={100} value={settings.major_limit} onChange={event => patch({ major_limit: Number(event.target.value) })} /></div><details><summary>Chance components & retained table choices</summary><div className="form-stack"><label className="check-row"><input type="checkbox" checked={!!settings.automatic_assessment} onChange={event => patch({ automatic_assessment: event.target.checked })} />Assess meaningful beats automatically</label><div className="recipe-field-grid">{components.map(([key, label]) => <label className="check-row" key={key}><input type="checkbox" checked={settings[key]} onChange={event => patch({ [key]: event.target.checked })} />{label}</label>)}</div><p className="subtle">Existing table versions, exclusions and texture assignments stay intact. Edit those detailed choices in Advanced recipe JSON.</p><pre className="writing-json">{JSON.stringify({ table_versions: settings.table_versions, disabled_tables: settings.disabled_tables, enabled_extras: settings.enabled_extras, excluded_rows: settings.excluded_rows, texture_tables: settings.texture_tables }, null, 2)}</pre></div></details></>}
  </section>
}
